#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyPodCast.Resource", IsApplication=true)]

namespace MyPodCast
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_by_genre = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_default_art = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_equalizer_white_24dp = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_notification = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_pause_white_24dp = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_play_arrow_white_24dp = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_shuffle_white_24dp = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_skip_next_white_24dp = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_skip_previous_white_24dp = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_star_off = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_star_on = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int btnNext = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int btnPlay = 2131099655;
			
			// aapt resource value: 0x7f060006
			public const int btnPrevious = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int containerMain = 2131099648;
			
			// aapt resource value: 0x7f060004
			public const int description = 2131099652;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060009
			public const int list_view = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int media_player = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int play_eq = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int title = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int media_list_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int media_player = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int automotive_app_desc = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
